.TH QCOIN-CLI "1" "June 2016" "qcoin-cli 0.12"
.SH NAME
qcoin-cli \- a remote procedure call client for Qcoin Core. 
.SH SYNOPSIS
qcoin-cli [options] <command> [params] \- Send command to Qcoin Core. 
.TP
qcoin-cli [options] help \- Asks Qcoin Core for a list of supported commands.
.SH DESCRIPTION
This manual page documents the qcoin-cli program. qcoin-cli is an RPC client used to send commands to Qcoin Core.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

.SH "SEE ALSO"
\fBqcoind\fP, \fBqcoin.conf\fP
.SH AUTHOR
This manual page was written by Ciemon Dunville <ciemon@gmail.com>. Permission is granted to copy, distribute and/or modify this document under the terms of the MIT License.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
